import { execSync } from 'child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, '..');
const scssDir = join(rootDir, 'src', 'scss');
const publicDir = join(rootDir, 'public');
const generatedDir = join(rootDir, 'src', 'app', 'generated');

function ensureDirectories() {
  if (!existsSync(publicDir)) mkdirSync(publicDir, { recursive: true });
  if (!existsSync(generatedDir)) mkdirSync(generatedDir, { recursive: true });
}

function generate() {
  console.log('[generate-css] Compiling Angular Material SCSS overrides...');

  try {
    ensureDirectories();

    // 1. Compile SCSS to CSS
    const compiledCss = execSync('npx sass --load-path=node_modules src/scss/_mat-overrides.scss', {
      cwd: rootDir,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'inherit'],
    });

    // 2. Read individual SCSS files
    const scssFilesList = [
      'sizes.scss',
      '_theme-colors.scss',
      'mat-button.scss',
      'mat-button-toggle.scss',
      'mat-checkbox.scss',
      'mat-chip.scss',
      'mat-form-field.scss',
      'mat-progress-bar.scss',
      'mat-radio-button.scss',
      'mat-slide-toggle.scss',
      'mat-slider.scss',
      '_mat-overrides.scss',
    ];

    const scssModules = [];
    let combinedScss = `// ============================================================================\n`;
    combinedScss += `// Angular Material Enhanced - Component Overrides (All-in-One SCSS)\n`;
    combinedScss += `// https://github.com/laudebugs/ng-material-enhanced\n`;
    combinedScss += `// ============================================================================\n\n`;

    for (const file of scssFilesList) {
      const filePath = join(scssDir, file);
      if (existsSync(filePath)) {
        const content = readFileSync(filePath, 'utf8');
        scssModules.push({ filename: file, content });

        combinedScss += `// ----------------------------------------------------------------------------\n`;
        combinedScss += `// File: ${file}\n`;
        combinedScss += `// ----------------------------------------------------------------------------\n`;
        combinedScss += content + '\n\n';
      }
    }

    // 3. Write public downloadable files
    const headerBanner = `/* ============================================================================\n * Angular Material Enhanced - Component Overrides (Compiled CSS)\n * Generated on: ${new Date().toISOString()}\n * https://github.com/laudebugs/ng-material-enhanced\n * ============================================================================ */\n\n`;
    const finalCss = headerBanner + compiledCss;

    writeFileSync(join(publicDir, 'material-overrides.css'), finalCss, 'utf8');
    writeFileSync(join(publicDir, 'material-overrides.scss'), combinedScss, 'utf8');

    // 4. Write TypeScript data file for the /css route
    const cssSizeKb = (Buffer.byteLength(finalCss, 'utf8') / 1024).toFixed(1);
    const scssSizeKb = (Buffer.byteLength(combinedScss, 'utf8') / 1024).toFixed(1);
    const cssLineCount = finalCss.split('\n').length;
    const scssLineCount = combinedScss.split('\n').length;

    const tsContent = `// Auto-generated by scripts/generate-css.mjs - DO NOT EDIT DIRECTLY
export interface ScssFileModule {
  filename: string;
  content: string;
}

export const GENERATED_AT = ${JSON.stringify(new Date().toISOString())};
export const CSS_SIZE_KB = ${JSON.stringify(cssSizeKb)};
export const SCSS_SIZE_KB = ${JSON.stringify(scssSizeKb)};
export const CSS_LINE_COUNT = ${cssLineCount};
export const SCSS_LINE_COUNT = ${scssLineCount};

export const COMPILED_CSS = ${JSON.stringify(finalCss)};
export const COMBINED_SCSS = ${JSON.stringify(combinedScss)};

export const SCSS_FILES: ScssFileModule[] = ${JSON.stringify(scssModules, null, 2)};
`;

    writeFileSync(join(generatedDir, 'css-overrides.data.ts'), tsContent, 'utf8');

    console.log(`[generate-css] Successfully generated:`);
    console.log(`  - public/material-overrides.css (${cssSizeKb} KB, ${cssLineCount} lines)`);
    console.log(`  - public/material-overrides.scss (${scssSizeKb} KB, ${scssLineCount} lines)`);
    console.log(`  - src/app/generated/css-overrides.data.ts`);
  } catch (err) {
    console.error('[generate-css] Error during generation:', err);
    process.exitCode = 1;
  }
}

// Check watch mode
const isWatch = process.argv.includes('--watch');

generate();

if (isWatch) {
  console.log('[generate-css] Watching src/scss for changes...');
  let debounceTimeout = null;
  import('fs').then(fs => {
    fs.watch(scssDir, { recursive: true }, (eventType, filename) => {
      if (filename && filename.endsWith('.scss')) {
        if (debounceTimeout) clearTimeout(debounceTimeout);
        debounceTimeout = setTimeout(() => {
          console.log(`[generate-css] File changed: ${filename}. Re-generating...`);
          generate();
        }, 300);
      }
    });
  });
}
